### ISSUE TITLE
Not finishing scan

### ISSUE THREAD

**Issue by ghost** [vadash/Path-of-Exile-modding-tool#1]
I've followed your instructions. When I click scan, after pasting the path to Content.ggpk, it just scans forever. Nothing ever happens..

**Comment by vadash** [comment]
Please check console window 
![image](https://user-images.githubusercontent.com/1397582/76986237-7175c600-6952-11ea-97b7-19e32041bbef.png)
First scan can take up to 20 minutes on HDD (up to 3 minutes SSD)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/50523899/76986555-1b008b80-6942-11ea-8cbf-d533ec17a301.png)
Hmm, I left it for like 30 minutes. Maybe my PC is just extra slow. I'll try to leave for an hour and see.

**Comment by vadash** [comment]
Can you check HDD load in task manager ?

![image](https://user-images.githubusercontent.com/1397582/76986792-32944000-6953-11ea-9e94-da75ba20028d.png)

**Comment by ghost** [comment]
It's 100%, so I guess it is doing something. Thanks :)
