### ISSUE TITLE
nothing happens after running start

### ISSUE THREAD

**Issue by pkfsa** [vadash/Path-of-Exile-modding-tool#10]
![Captured](https://user-images.githubusercontent.com/51827887/87800320-3f02a980-c81c-11ea-9030-e008169e8c25.PNG)
this is all that happens, i cannot proceed to the next step

**Comment by vadash** [comment]
Navigate to `Path-of-Exile-modding-tool\normal` and click `__init__.py` directly

**Comment by pkfsa** [comment]
That worked but now I am getting permission denied. I already set access to everyone.

**Comment by vadash** [comment]
Close game ? Move ggpk to another place then back

**Comment by pkfsa** [comment]
I fixed it by moving my path of exile install to my main hd where python is installed
