### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by happynexra** [vadash/Path-of-Exile-modding-tool#12]
I often crash upon entering maps since enabling "reduced effects" and "remove corpses"
its not specific maptiles, but instances, was never crashing (like this) before using this tool. Im on a lowend laptop nvidia 950m and while this has IMMENSELY improved performance, these crashes are annoying. Any tips? I have recently defragged .gppk and cleared shader caches, and sometimes its crash from loadscreen, one time i was able to enter the map for a second before crash.

**Comment by vadash** [comment]
Can you test with removed keep folder, fresh ggpk and only option "reduced effects" ?

**Comment by vadash** [comment]
did 15 maps with recommended preset - 0 crashes so far

**Comment by happynexra** [comment]
Sorry, what do you mean removed keep folder? And yeah, I was considering to reinstall the whole game because other than defragging and clearing caches I have had the same installation for over 6 years. Will probably get around to it this weekend. 
I was probably crashing less than every 15 maps, hard to say a number since it seemed to be an incident that was specific to the instance (portals still up, but entering after reopening game still crashes.) On a technical level, how could it be related to removing corpses? since it happens before I even move let alone kill anything.

**Comment by vadash** [comment]
If u crashing because of ggpk mods no amount of reopening will fix it

**Comment by vadash** [comment]
And for keep folder read readme :D

**Comment by kunitsu** [comment]
Yea.. about the crashing, I did the testing with only the "reduced effects" applied.

For me it's crashing on act 3, upon entering "Lunaris temple level 1", i tried some debugging but got nothing =/ (I know python but nothing on ggpk sadly hehe)

Thanks for the work tho, really appreciated! For the first time I was able to play the game seeing things and without losing frames :]

**Comment by vadash** [comment]
Thats what I want to hear. Managed to reproduce crash

**Comment by vadash** [comment]
![image](https://user-images.githubusercontent.com/1397582/87873360-ba558e00-c9c9-11ea-847e-5a8f86263169.png)
After fix

**Comment by vadash** [comment]
I also returned old option when u remove all emitters 
![image](https://user-images.githubusercontent.com/1397582/87873370-d1947b80-c9c9-11ea-8524-56c11c406a14.png)
