### ISSUE TITLE
Screen almost completely black during Alva incursion

### ISSUE THREAD

**Issue by pkfsa** [vadash/Path-of-Exile-modding-tool#13]
I've used the following settings:
-Reduce spell effects
-Disable fog,shadows,etc
-Remove dead bodies
-Remove monster (non boss) sounds

I can see only the hud, everything else is black.

**Comment by vadash** [comment]
gpu ? all good here 
![image](https://user-images.githubusercontent.com/1397582/87885142-45f80a80-ca1c-11ea-98ff-88dcc8d1035d.png)

**Comment by vadash** [comment]
Type in green box
`hlsl$`
`ffx$`
![image](https://user-images.githubusercontent.com/1397582/88370593-f8bcc580-cd9a-11ea-9e13-c26e49dfdcd9.png)

Click search -> restore (near search)
![image](https://user-images.githubusercontent.com/1397582/88370647-1a1db180-cd9b-11ea-9bfa-b1dfed598002.png)

It most likely one of shaders from `Path-of-Exile-modding-tool\normal\extracted\Shaders`

![image](https://user-images.githubusercontent.com/1397582/88370681-315c9f00-cd9b-11ea-98b6-3eeb973ab8a3.png)

Remove them 1 by 1 and test if u want. I dont have AMD GPU anymore

**Comment by vadash** [comment]
![image](https://user-images.githubusercontent.com/1397582/88739254-cddbc400-d142-11ea-8183-d42376e55253.png)
