### ISSUE TITLE
Errno13 after giving permissions

### ISSUE THREAD

**Issue by Tosi13** [vadash/Path-of-Exile-modding-tool#14]
First of all, thanks for creating this script for people with bad pc's like mine.

Unfortunely, i can't get it to work on my pc, everything has full control enabled, content.ggpk, the .bat and .py files, and the whole path of exile folder, and i still get this error. Im on python 3.7.5 since i already had it installed, but i don't think that's the issue.

Any help is accepted, thanks :)

Edit: updated python to 3.8.5, nothing changed.

**Comment by vadash** [comment]
Move game and script to same disk. Dont use long path (256 max). Post error screen

I use it on GTX1070 since I like clean image and 144 fps as well ;)

**Comment by Tosi13** [comment]
https://i.imgur.com/gFMMsxf.png

They're on the same disk. I've tried some solutions on my own like giving permissions to all the stuff in program files and other, but my python knowledge is limited :P

**Comment by vadash** [comment]
path is wrong

**Comment by Tosi13** [comment]
The game path? Or where the bat should be? I double checked paths and they seem fine

edit: installed game in E drive instead of C, that fixed it, thanks.

**Comment by vadash** [comment]
For future users correct path looks like

**C:\games\poe\Content.ggpk**

**Comment by bigupAB** [comment]
UPDATE: I have figured out my error. I did not include content.ggpk in the filepath. 
Thank you for this tool. I have went from 60 fps on dx11 to 100+ 

I have tried F:\games\poe\ and E:\games\poe\, both will full everyone perms as outlined in your guide.
i've also checked every file to make sure read only wasn't enabled. 

Unfortunately I still receive a perm denied error. Any ideas?
