### ISSUE TITLE
Much lower boss performance since update

### ISSUE THREAD

**Issue by Socom12** [vadash/Path-of-Exile-modding-tool#17]
Hi, I recently updated the tool, and now sirus causes fps drops, and oshabi is now unplayable with how much frame dropping there is, using these settings.
https://i.imgur.com/392JxdI.png
Is there a way to get the performance of the previous tool build back, or will the remove all effects option give me my performance back?

**Comment by vadash** [comment]
I added all bosses to exclude list since its pain in the ass to debug what to remove

Invisible volatiles, invisible auras, invisible sirius walls, storms etc

**Comment by Socom12** [comment]
Ah alright, I'll just stick to an older build since that worked perfectly fine. I'm not sure how much the newer build's options would improve my performance over the current build I use, if I were to change the exlude to be back to what it is for me now.

Is there a way to improve fps in a grove, though? It's always so laggy in groves due to all the storage tanks and etc.

**Comment by vadash** [comment]
> Is there a way to improve fps in a grove, though? It's always so laggy in groves due to all the storage tanks and etc.

Sure, if harvest garden goes core I will look into it
