### ISSUE TITLE
[Feature] Is it possible to resize textures like in original fork?

### ISSUE THREAD

**Issue by SakhG** [vadash/Path-of-Exile-modding-tool#19]

**Comment by vadash** [comment]
It was replacing them with uncompressed. It didnt help at all. To do it properly you need to use extra tool like Ordinator

![image](https://user-images.githubusercontent.com/1397582/89210712-47533680-d5c9-11ea-867e-0044921c9f4b.png)

**Comment by SakhG** [comment]
So if I compress them properly with 3rd party tool, what am I suppose to do?
Put them in "extracted" and hit "insert"?

**Comment by vadash** [comment]
Yep. It may take a while to insert everything. I didnt get any performance increase on shittiest GPU i had (1050 2 GB)
