### ISSUE TITLE
"Insert"

### ISSUE THREAD

**Issue by softwarnet** [vadash/Path-of-Exile-modding-tool#2]
After all modifications "insert" button do nothing.
Mean that 5 files,that you notice in the description do no change.
So delirim fog is bricked.
W10 x64,steam version of POE

**Comment by vadash** [comment]
You can restart app and try to insert again

**Comment by softwarnet** [comment]
Is this directly relate to the "modify" command?
I mean,could i do it in the second or even third launch,or should it being done immediately after modification?

**Comment by softwarnet** [comment]
I'm retard.It's ok now.
Could you please, leave a warning for 2heads from Russia regarding the fact that "insert" is not a button on the keyboard?
