### ISSUE TITLE
brotli error

### ISSUE THREAD

**Issue by spainenins** [vadash/Path-of-Exile-modding-tool#4]
So I used this tool on my laptop with windows 8.1, everything worked well.
Now I installed windows 10 on the same computer, downloaded python, installed pip, downloaded fresh poe, downloaded latest version of this tool and when I open it, this error shows up.
Is there anything I have not done?

![poemtm_error](https://user-images.githubusercontent.com/64022197/79761126-e6337b80-82d5-11ea-8932-cbe51feb520b.png)

**Comment by vadash** [comment]
run cmd and type python
![image](https://user-images.githubusercontent.com/1397582/79764699-62f24400-832e-11ea-936a-151f5ae04756.png)

**Comment by vadash** [comment]
Everything looks fine in log. Try another python build / reinstall vcredist https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by spainenins** [comment]
First, I tried reinstalling vcredist, nothing changed.
Then I installed python 3.7.7 and the tool works fine!
Thanks for quick response!
