### ISSUE TITLE
Desecrated ground exclude filter

### ISSUE THREAD

**Issue by MBoBr** [vadash/Path-of-Exile-modding-tool#6]
Hi, I'm using your tool to remove dd/vd/desecrate effects but it seems like it also removes patches of desecrated ground from maps and it's kinda dangerous mod, can you give me key words for exclude filter so I restore desecrated ground.
Привет, можешь дать ключевые слова для фильтра, чтобы восстановить эффекты de, в поиске что-то не нашел ):

**Comment by MBoBr** [comment]
Путем нехитрых манипуляций с нампадом вернул десикрейт, не знаю какая строчка там за что отвечает, поэтому убрал все пока что, засирает экран конечно, но зато и мап-мод виден.

**Comment by vadash** [comment]
/ground_effects
вот это в исключение, поправил
