### ISSUE TITLE
Removing delirium fog

### ISSUE THREAD

**Issue by snusmanager** [vadash/Path-of-Exile-modding-tool#7]
Delirium fog files seem to be missing, maybe the update for the removal process is needed?

**Comment by vadash** [comment]
Looks alright after GGG fix and 0 performance hit. I see no reason to remove

**Comment by snusmanager** [comment]
I meant the README file. It says to use specific files which are not present in your repository. Probably you should refresh the information on where to get them, because there's nothing in my "optional" folder that is even remotely comparable to what is in your instruction. Sorry if my first message was a bit misleading, appreciate your work.

**Comment by vadash** [comment]
Thanks. Delirium fog is back (few users reported it helpful)
