### ISSUE TITLE
no "blackscreen" folder in downloaded repo.

### ISSUE THREAD

**Issue by cyberbiosecurity** [vadash/Path-of-Exile-modding-tool#8]
Hi.
I've downloaded the codebase.
I've started reading the README.md. 
It currently says that I need to copy files from [Path-of-Exile-modding-tool\optional\blackscreen] to [Path-of-Exile-modding-tool\extracted].
But there is no such folder "blackscreen" in the downloaded archives - both downloaded via "Download zip" option above the repo itself and via the link provided in the README.md [https://github.com/vadash/Path-of-Exile-modding-tool/archive/master.zip].
Here's the folder structure I get out of the archive:
root\Path-of-Exile-modding-tool-master
root\Path-of-Exile-modding-tool-master\bot
root\Path-of-Exile-modding-tool-master\normal
root\Path-of-Exile-modding-tool-master\bot\assets
root\Path-of-Exile-modding-tool-master\bot\automods
root\Path-of-Exile-modding-tool-master\bot\extracted
root\Path-of-Exile-modding-tool-master\bot\mods
root\Path-of-Exile-modding-tool-master\bot\extracted\Shaders
root\Path-of-Exile-modding-tool-master\bot\extracted\Shaders\Renderer
root\Path-of-Exile-modding-tool-master\normal\assets
root\Path-of-Exile-modding-tool-master\normal\automods
root\Path-of-Exile-modding-tool-master\normal\mods
root\Path-of-Exile-modding-tool-master\normal\optional
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia\Metadata
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia\Shaders
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia\Metadata\EnvironmentSettings
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia\Metadata\EnvironmentSettings\ShaderGather
root\Path-of-Exile-modding-tool-master\normal\optional\nvidia\Shaders\Renderer

Thank you.

**Comment by D0N-B0T** [comment]
We need an answer for this.

**Comment by vadash** [comment]
I removed bot preset for now

**Comment by vadash** [comment]
blackscreen is only for bots

**Comment by DirtyChets** [comment]
why bot preset was deleted?

**Comment by vadash** [comment]
I will return it after rework in another repo

**Comment by DirtyChets** [comment]
If that's no secret, what changes are you going to make?
